### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by DanielZanchi** [runpod-workers/worker-sdxl#7]
Compared to the https://replicate.com/stability-ai/sdxl some parameters like _high_noise_frac_ are missing. Can we have those?

**Comment by DanielZanchi** [comment]
Any update on this?

**Comment by DanielZanchi** [comment]
What about the NSFW filter?

**Comment by justinmerrell** [comment]
Has Hugging Face exposed this as an easy-to-use parameter yet?
